# Generated by scripts/codegen/policy_mirror.py. Do not edit by hand.
from __future__ import annotations

import hashlib
import json
from typing import Any


POLICY_SCHEMA = {
  "actions": {
    "approval:review": {
      "allowedRoles": [
        "admin",
        "reviewer"
      ],
      "defaultApprovalPath": "auto",
      "requiredPolicyKeys": [],
      "ruleRef": "R25"
    },
    "budget:raise": {
      "allowedRoles": [
        "admin"
      ],
      "defaultApprovalPath": "admin",
      "requiredPolicyKeys": [
        "budget_cap_raise"
      ],
      "ruleRef": "R16"
    },
    "campaign:cancel": {
      "allowedRoles": [
        "admin",
        "operator"
      ],
      "defaultApprovalPath": "auto",
      "requiredPolicyKeys": [
        "campaign_cancel"
      ],
      "ruleRef": "R24"
    },
    "campaign:create": {
      "allowedRoles": [
        "admin",
        "operator"
      ],
      "defaultApprovalPath": "auto",
      "requiredPolicyKeys": [],
      "ruleRef": "R3,R9"
    },
    "campaign:run": {
      "allowedRoles": [
        "admin",
        "operator"
      ],
      "defaultApprovalPath": "auto",
      "requiredPolicyKeys": [],
      "ruleRef": "R9"
    },
    "data_mode:flip_real_phi": {
      "allowedRoles": [
        "admin"
      ],
      "defaultApprovalPath": "admin",
      "requiredPolicyKeys": [
        "data_mode_flip_real_phi",
        "baa_acknowledged"
      ],
      "ruleRef": "R16"
    },
    "documentation:draft": {
      "allowedRoles": [],
      "defaultApprovalPath": "auto",
      "requiredPolicyKeys": [
        "documentation_draft"
      ],
      "ruleRef": "R16"
    },
    "finding:triage": {
      "allowedRoles": [
        "admin",
        "operator",
        "reviewer"
      ],
      "defaultApprovalPath": "auto",
      "requiredPolicyKeys": [],
      "ruleRef": "R12"
    },
    "judge:verdict": {
      "allowedRoles": [],
      "defaultApprovalPath": "auto",
      "requiredPolicyKeys": [
        "judge_verdict",
        "judge_calibration_threshold"
      ],
      "ruleRef": "R16"
    },
    "low_signal:stop_rule": {
      "allowedRoles": [],
      "defaultApprovalPath": "auto",
      "requiredPolicyKeys": [
        "low_signal_stop_rule"
      ],
      "ruleRef": "R16"
    },
    "orchestrator:new_category": {
      "allowedRoles": [],
      "defaultApprovalPath": "reviewer",
      "requiredPolicyKeys": [
        "orchestrator_new_category"
      ],
      "ruleRef": "R16"
    },
    "orchestrator:regression_sweep": {
      "allowedRoles": [],
      "defaultApprovalPath": "auto",
      "requiredPolicyKeys": [
        "orchestrator_regression_sweep"
      ],
      "ruleRef": "R16"
    },
    "policy:write": {
      "allowedRoles": [
        "admin"
      ],
      "defaultApprovalPath": "admin",
      "requiredPolicyKeys": [
        "policy:write"
      ],
      "ruleRef": "R15"
    },
    "red_team:mutate_seed": {
      "allowedRoles": [],
      "defaultApprovalPath": "auto",
      "requiredPolicyKeys": [
        "red_team_mutate_med",
        "red_team_mutate_high_critical",
        "red_team_pending_cap"
      ],
      "ruleRef": "R16"
    },
    "red_team:new_category": {
      "allowedRoles": [],
      "defaultApprovalPath": "reviewer",
      "requiredPolicyKeys": [
        "red_team_new_category"
      ],
      "ruleRef": "R16"
    },
    "regression:promote": {
      "allowedRoles": [
        "admin",
        "reviewer"
      ],
      "defaultApprovalPath": "reviewer",
      "requiredPolicyKeys": [
        "regression_promote"
      ],
      "ruleRef": "R16"
    },
    "report:publish": {
      "allowedRoles": [
        "admin",
        "reviewer"
      ],
      "defaultApprovalPath": "reviewer",
      "requiredPolicyKeys": [
        "report_publish"
      ],
      "ruleRef": "R16"
    },
    "schedule:manage": {
      "allowedRoles": [
        "admin"
      ],
      "defaultApprovalPath": "admin",
      "requiredPolicyKeys": [
        "orchestrator_sweep_cadence"
      ],
      "ruleRef": "R21"
    },
    "secret:manage": {
      "allowedRoles": [
        "admin"
      ],
      "defaultApprovalPath": "admin",
      "requiredPolicyKeys": [],
      "ruleRef": "R22"
    },
    "seed:promote": {
      "allowedRoles": [
        "admin",
        "reviewer"
      ],
      "defaultApprovalPath": "reviewer",
      "requiredPolicyKeys": [
        "regression_promote"
      ],
      "ruleRef": "R16"
    },
    "target:allowlist_add": {
      "allowedRoles": [
        "admin"
      ],
      "defaultApprovalPath": "admin",
      "requiredPolicyKeys": [
        "target_allowlist_add"
      ],
      "ruleRef": "R16"
    },
    "target:manage": {
      "allowedRoles": [
        "admin"
      ],
      "defaultApprovalPath": "admin",
      "requiredPolicyKeys": [
        "target_allowlist_add"
      ],
      "ruleRef": "R16"
    }
  },
  "approvalPaths": [
    "auto",
    "reviewer",
    "admin",
    "deny"
  ],
  "pathRank": {
    "admin": 2,
    "auto": 0,
    "deny": 3,
    "reviewer": 1
  },
  "roleActions": {
    "admin": [
      "campaign:create",
      "campaign:run",
      "campaign:cancel",
      "finding:triage",
      "target:manage",
      "policy:write",
      "seed:promote",
      "approval:review",
      "secret:manage",
      "schedule:manage",
      "report:publish",
      "regression:promote",
      "target:allowlist_add",
      "data_mode:flip_real_phi",
      "budget:raise"
    ],
    "operator": [
      "campaign:create",
      "campaign:run",
      "campaign:cancel",
      "finding:triage"
    ],
    "reviewer": [
      "finding:triage",
      "seed:promote",
      "approval:review",
      "report:publish",
      "regression:promote"
    ]
  },
  "roles": [
    "admin",
    "operator",
    "reviewer"
  ],
  "systemReservedRows": {
    "baa_acknowledged": {
      "minApprovalPath": "admin",
      "ruleRef": "R16"
    },
    "data_mode_flip_real_phi": {
      "minApprovalPath": "admin",
      "ruleRef": "R16"
    },
    "policy:write": {
      "minApprovalPath": "admin",
      "ruleRef": "R15"
    },
    "red_team_mode": {
      "minApprovalPath": "admin",
      "ruleRef": "R16"
    },
    "target_allowlist_add": {
      "minApprovalPath": "admin",
      "ruleRef": "R16"
    }
  },
  "version": 1
}
ACTIONS = tuple(['approval:review', 'budget:raise', 'campaign:cancel', 'campaign:create', 'campaign:run', 'data_mode:flip_real_phi', 'documentation:draft', 'finding:triage', 'judge:verdict', 'low_signal:stop_rule', 'orchestrator:new_category', 'orchestrator:regression_sweep', 'policy:write', 'red_team:mutate_seed', 'red_team:new_category', 'regression:promote', 'report:publish', 'schedule:manage', 'secret:manage', 'seed:promote', 'target:allowlist_add', 'target:manage'])
ROLES = tuple(['admin', 'operator', 'reviewer'])
ROLE_ACTIONS = {
  "admin": [
    "campaign:create",
    "campaign:run",
    "campaign:cancel",
    "finding:triage",
    "target:manage",
    "policy:write",
    "seed:promote",
    "approval:review",
    "secret:manage",
    "schedule:manage",
    "report:publish",
    "regression:promote",
    "target:allowlist_add",
    "data_mode:flip_real_phi",
    "budget:raise"
  ],
  "operator": [
    "campaign:create",
    "campaign:run",
    "campaign:cancel",
    "finding:triage"
  ],
  "reviewer": [
    "finding:triage",
    "seed:promote",
    "approval:review",
    "report:publish",
    "regression:promote"
  ]
}
SYSTEM_RESERVED_ROWS = {
  "baa_acknowledged": {
    "minApprovalPath": "admin",
    "ruleRef": "R16"
  },
  "data_mode_flip_real_phi": {
    "minApprovalPath": "admin",
    "ruleRef": "R16"
  },
  "policy:write": {
    "minApprovalPath": "admin",
    "ruleRef": "R15"
  },
  "red_team_mode": {
    "minApprovalPath": "admin",
    "ruleRef": "R16"
  },
  "target_allowlist_add": {
    "minApprovalPath": "admin",
    "ruleRef": "R16"
  }
}
APPROVAL_PATH_RANK = POLICY_SCHEMA["pathRank"]


def can(role: str, action: str) -> bool:
    return action in ROLE_ACTIONS.get(role, ())


def canonical_hash(value: Any) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def canonical_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"))


def required_policy_keys(action: str) -> tuple[str, ...]:
    return tuple(POLICY_SCHEMA["actions"][action]["requiredPolicyKeys"])


def minimum_approval_path(key: str) -> str | None:
    row = SYSTEM_RESERVED_ROWS.get(key)
    if not row:
        return None
    return row["minApprovalPath"]


def approval_path_allows(candidate: str, floor: str) -> bool:
    return APPROVAL_PATH_RANK.get(candidate, -1) >= APPROVAL_PATH_RANK[floor]
