from __future__ import annotations

import json
import sys
from pathlib import Path


def main() -> None:
    schema_path = Path(sys.argv[1] if len(sys.argv) > 1 else "worker/policy-schema.json")
    output_path = Path(sys.argv[2] if len(sys.argv) > 2 else "worker/safety_gate.py")
    schema = json.loads(schema_path.read_text(encoding="utf-8"))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render(schema), encoding="utf-8")


def render(schema: dict) -> str:
    actions = sorted(schema["actions"].keys())
    roles = schema["roles"]
    role_actions = schema["roleActions"]
    reserved = schema["systemReservedRows"]

    return f'''# Generated by scripts/codegen/policy_mirror.py. Do not edit by hand.
from __future__ import annotations

import hashlib
import json
from typing import Any


POLICY_SCHEMA = {json.dumps(schema, indent=2, sort_keys=True)}
ACTIONS = tuple({actions!r})
ROLES = tuple({roles!r})
ROLE_ACTIONS = {json.dumps(role_actions, indent=2, sort_keys=True)}
SYSTEM_RESERVED_ROWS = {json.dumps(reserved, indent=2, sort_keys=True)}
APPROVAL_PATH_RANK = POLICY_SCHEMA["pathRank"]


def can(role: str, action: str) -> bool:
    return action in ROLE_ACTIONS.get(role, ())


def canonical_hash(value: Any) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def canonical_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"))


def required_policy_keys(action: str) -> tuple[str, ...]:
    return tuple(POLICY_SCHEMA["actions"][action]["requiredPolicyKeys"])


def minimum_approval_path(key: str) -> str | None:
    row = SYSTEM_RESERVED_ROWS.get(key)
    if not row:
        return None
    return row["minApprovalPath"]


def approval_path_allows(candidate: str, floor: str) -> bool:
    return APPROVAL_PATH_RANK.get(candidate, -1) >= APPROVAL_PATH_RANK[floor]
'''


if __name__ == "__main__":
    main()
